### PR TITLE
http client proxy

### PR DESCRIPTION
**Pull request by effoeffi**

### CODE REVIEW

**Comment by PhilippHeuer** [comment]
There is no convention in regards to upper / lowercase for http proxy env vars, so checking for both `http_proxy, https_proxy` and `HTTP_PROXY, HTTPS_PROXY` is usually a good way. You also don't evaluate values set in `no_proxy` / `NO_PROXY`.

https://pkg.go.dev/golang.org/x/net/http/httpproxy provides a `FromEnvironment` function to parse these values and also provides helper methods to evaluate `no_proxy` to decide if the proxy should be used or not based on the url. (https://cs.opensource.google/go/x/net/+/refs/tags/v0.15.0:http/httpproxy/proxy.go;l=89)

**Comment by effoeffi** [comment]
> There is no convention in regards to upper / lowercase for http proxy env vars, so checking for both `http_proxy, https_proxy` and `HTTP_PROXY, HTTPS_PROXY` is usually a good way. The current implementation also doesn't cover `no_proxy` / `NO_PROXY` yet.
> 
> https://pkg.go.dev/golang.org/x/net/http/httpproxy provides a `FromEnvironment` function to parse these values and also provides helper methods to evaluate `no_proxy` to decide if the proxy should be used or not based on the url. (https://cs.opensource.google/go/x/net/+/refs/tags/v0.15.0:http/httpproxy/proxy.go;l=89)

Great references, thanks! Created a [PR](https://github.com/oasdiff/go-common/pull/2) with your suggestion in our go-common repo, and added you as a contributor. Please add your review.

**Comment by PhilippHeuer** [comment]
Technically this would be enough to set-up a http client:

```
client := http.Client{
    Transport: &http.Transport{
        Proxy: http.ProxyFromEnvironment,
    },
}
```

I didn't know this before, but `http.Client` has a `DefaultTransport` that is used if `Transport` is nil - the `DefaultTransport` also sets the same line to configure the proxy - so a client created with `http.Client{}` already supports proxies.

This might make this change obsolete if we don't need a custom transport / don't need to customize the default timeout.

**Comment by effoeffi** [comment]
>I didn't know this before, but http.Client has a DefaultTransport that is used if Transport is nil - the DefaultTransport also sets the same line to configure the proxy - so a client created with http.Client{} already supports proxies.

You are right, but not just a client that created with `http.Client{}`, also when running it like I did at the beginning. Tested it with the follow:
```
func TestProxy(t *testing.T) {

	require.NoError(t, os.Setenv("HTTPS_PROXY", "https://localhost:8080"))
	_, err := http.Get("https://google.com")
	require.NoError(t, err)
}
```
result:
```
Received unexpected error: Get "https://google.com": proxyconnect tcp: dial tcp 127.0.0.1:8080: connect: connection refused

**Pull request merged**
